name: Google Indexing Automation

on:
  schedule:
    - cron: '0 0 * * *' # Fires every single night at midnight automatically
  workflow_dispatch: # Gives you a manual button to click whenever you launch an SEO cluster

jobs:
  google-indexing:
    runs-on: ubuntu-latest
    steps:
      - name: Send Sitemap to Google Indexing API
        uses: robingenz/action-google-indexing@v1.0.0
        with:
          siteUrl: 'https://qr.alfo.online'
          gcpServiceAccountKey: ${{ secrets.GCP_SA_KEY }}
