import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | QRBuild - QR Code Generator",
  description: "Important disclaimer for QRBuild users regarding QR code usage, content responsibility, and service limitations.",
  alternates: {
    canonical: "/disclaimer",
  },
};

export default function DisclaimerPage() {
  return (
    <div className="py-20 max-w-4xl mx-auto px-4">
      <h1 className="font-display text-4xl font-bold mb-8">Disclaimer</h1>
      <div className="prose prose-slate max-w-none">
        <p>Last updated: January 2025</p>
        
        <p className="text-lg mb-6">
          By using QRBuild, you acknowledge and agree to the following disclaimers. Please read this information carefully before using our QR code generation service.
        </p>

        <h2>1. No Responsibility for QR Code Content</h2>
        <p>
          QRBuild is a tool that generates QR codes based on user-provided input. We do not monitor, control, or verify the content embedded in the QR codes you create. You are solely responsible for ensuring that the URLs, text, contact information, or other data you encode comply with all applicable laws and regulations.
        </p>
        <p>
          We expressly disclaim any responsibility for:
        </p>
        <ul>
          <li>The accuracy, legality, or appropriateness of content encoded in QR codes</li>
          <li>Any damages resulting from scanning QR codes generated through our service</li>
          <li>Misuse of QR codes created using QRBuild by you or third parties</li>
          <li>Any malicious content that may be linked through QR codes generated on our platform</li>
        </ul>

        <h2>2. No Warranty on Scannability</h2>
        <p>
          While we strive to generate high-quality QR codes that are compatible with most scanners, we cannot guarantee that every QR code will be scannable by all devices or QR code readers. Factors such as printing quality, screen resolution, lighting conditions, and the specific scanner app used can affect scannability.
        </p>
        <p>
          We recommend testing your QR codes before distributing them widely, especially for critical applications such as marketing materials, product packaging, or important documents.
        </p>

        <h2>3. Not Responsible for Linked Content</h2>
        <p>
          If you create a QR code that links to a website or online resource, QRBuild has no control over and assumes no responsibility for the content, privacy policies, or practices of any third-party websites. We strongly encourage you to review the terms and policies of any site you link to.
        </p>
        <p>
          We are not liable for any damage or loss caused by your use of or reliance on any content, goods, or services available on or through any such external sites.
        </p>

        <h2>4. Accuracy of Information</h2>
        <p>
          The QR codes generated by QRBuild are created based on the exact input you provide. We do not verify, validate, or correct the information you enter. It is your responsibility to ensure that:
        </p>
        <ul>
          <li>URLs are correct and lead to the intended destination</li>
          <li>Contact information (phone numbers, email addresses) is accurate</li>
          <li>WiFi credentials are entered correctly</li>
          <li>Any other encoded data is free from errors</li>
        </ul>

        <h2>5. Service Availability</h2>
        <p>
          While we aim to maintain continuous service availability, QRBuild is provided on an "as is" and "as available" basis. We do not warrant that:
        </p>
        <ul>
          <li>The service will be uninterrupted, timely, or error-free</li>
          <li>Defects will be corrected</li>
          <li>The service or servers are free of viruses or harmful components</li>
        </ul>

        <h2>6. No Professional Advice</h2>
        <p>
          The content and tools provided on QRBuild are for general informational and utility purposes only. Nothing on this website constitutes professional advice, technical consultation, or legal guidance. For specific needs related to QR code implementation in business, marketing, or security-critical applications, please consult with qualified professionals.
        </p>

        <h2>7. Changes to This Disclaimer</h2>
        <p>
          We reserve the right to modify this disclaimer at any time without prior notice. Your continued use of QRBuild after any changes indicates your acceptance of the updated disclaimer. We encourage you to review this page periodically for any updates.
        </p>

        <h2>8. Contact Us</h2>
        <p>
          If you have any questions or concerns about this disclaimer, please contact us:
        </p>
        <ul>
          <li>Through our <a href="/contact" className="text-cta hover:underline">Contact page</a></li>
          <li>Via email at: <a href="mailto:alfotech.official@gmail.com" className="text-cta hover:underline">alfotech.official@gmail.com</a></li>
        </ul>
      </div>
    </div>
  );
}
